### PR TITLE
v1.3.1

### PR DESCRIPTION
**Pull request by douglance**
**Fixes:**

* (#390) [Converts chainId to number as expected by integrations](https://github.com/GridPlus/gridplus-sdk/pull/392/commits/f8bbf89f6d1d41703a2e7110e377a4cc59f25142)
* #393 
* #394 

**Misc:**

* (#389) [Removes .env file from build process](https://github.com/GridPlus/gridplus-sdk/pull/392/commits/0342a1e8b97931a7105d1d5f8f880ad3b2b37824)
* (#391) [Updates publish workflow](https://github.com/GridPlus/gridplus-sdk/pull/392/commits/dfd64625492d4b9424998f0976c44ee025e7e421)
* (#395) [Organizes imports for util file](https://github.com/GridPlus/gridplus-sdk/pull/392/commits/5901a26ceb1e0f21c8dd885c6f11bc871e587b7a)

### CODE REVIEW

**Comment by douglance** [comment]
@alex-miller-0 yeah--those have been there for a bit. We can clean them up in the next one, unless you'd prefer them gone now.

**Comment by douglance** [comment]
@alex-miller-0 Fixed sanity check [5901a26](https://github.com/GridPlus/gridplus-sdk/pull/392/commits/5901a26ceb1e0f21c8dd885c6f11bc871e587b7a)

**Review by KevinVitale — CHANGES_REQUESTED** [review]
@douglance has found #394 isn't fixed with these changes. Requesting changes to this PR until we can fix it.

**Review by KevinVitale — APPROVED** [review]
Issues with #394 will be fixed after shipping v1.3.1. Carry on.

**Comment by KevinVitale** [comment]
Would wait for @alex-miller-0 to approve as well since this will be a published release.

**Review by alex-miller-0 — APPROVED** [review]

**Pull request merged**
