### PR TITLE
Migrates latest README to docs

### PR DESCRIPTION
**Pull request by douglance**
To test: 
- pull this branch
- `cd docs`
- `npm i`
- `npm run start`
- Open localhost:3000 in the browser

### CODE REVIEW

**Review by alex-miller-0 — COMMENTED** [review]
Looks good! One suggestion would be to document the other things that are exported from `index` (`Client`, `Utils`, and `Constants`). That may require a new markdown file. I guess it doesn't have to be in this PR but we should get that stuff written down.

Btw how does this build process work? We only want to rebuild docs when `main` gets new commits, right? I'm assuming there is some sort of hook in this repo for that, but please confirm.

**Comment by douglance** [comment]
> Looks good! One suggestion would be to document the other things that are exported from `index` (`Client`, `Utils`, and `Constants`). That may require a new markdown file. I guess it doesn't have to be in this PR but we should get that stuff written down.

I can add that here. It can be automated. 
 
> Btw how does this build process work? We only want to rebuild docs when `main` gets new commits, right? I'm assuming there is some sort of hook in this repo for that, but please confirm.

Yep. It builds the docs on PRs and other branches, just to make sure it still works. But only pushes it live on pushes to `main`.

**Comment by douglance** [comment]
@alex-miller-0 The requested changes are in [c8fe596](https://github.com/GridPlus/gridplus-sdk/pull/380/commits/c8fe5961a27e739c1087120524883af9920ccec9).

**Comment by alex-miller-0** [comment]
@douglance don't you need to pay attention to case here? Not sure how these were generated, but its `Util`, `Constants`, and `Calldata` (where `Calldata`'s only accessible attribute is `EVM`)

**Comment by douglance** [comment]
[I had to open a PR in a library to customize those labels](https://github.com/tgreyuk/typedoc-plugin-markdown/pull/308).

**Comment by alex-miller-0** [comment]
Nice. Okay well we can just merge this in for now and update it later

**Review by alex-miller-0 — APPROVED** [review]

**Pull request merged**
