### PR TITLE
Upgrades to TypeScript

### PR DESCRIPTION
**Pull request by douglance**
This PR upgrades the codebase to TypeScript. There are a lot of changes here, which I tried to avoid as much as I could, but yeah a lot of them were necessary. 

I tried to commit as often as possible so you could step through the changes.

### CODE REVIEW

**Comment by alex-miller-0** [comment]
@douglance how did you decide what changes to make? Did you run this through a linter?

**Comment by douglance** [comment]
@alex-miller-0 Yep. There's eslint with TypeScript plugins running, as well as the TypeScript language server that is checking types. 

I lowered the strictness of the rules and disabled some to avoid making too many changes, but even then there were a lot of issues that I felt were worth addressing.

**Review by KevinVitale — APPROVED** [review]

**Comment by alex-miller-0** [comment]
Integration tests against `0.13.0` release candidate:

- [x] `test`
- [ ] `test-abi`
- [ ] `test-eth`
- [ ] `test-eth-msg`
- [ ] `test-btc`
- [ ] `test-kv`
- [ ] `test-wallet-jobs`
- [ ] `test-sigs`

**Comment by douglance** [comment]
@alex-miller-0 I believe those tests should be passing now.

**Comment by alex-miller-0** [comment]
- [x] `test`
- [x] `test-abi` 
- [x] `test-eth` 
- [x] `test-eth-msg` 
- [x] `test-btc`
- [ ] `test-kv` - failed, but I think it was an edge case in the test and device state
- [ ] `test-wallet-jobs` ❌  
- [x] `test-sigs`

`test-kv`:

```


`test-wallet-jobs`: (same error multiple times)

```
  1) Test leading zeros
       Should test address m/44'/60'/0'/0/396 (1 leading zero byte):
     TypeError: Cannot read property 'decode' of undefined
      at /Users/alexmiller/Projects/new-gridplus/tools/gridplus-sdk/test/testWalletJobs.ts:751:30
      at step (test/testWalletJobs.ts:33:23)
      at Object.next (test/testWalletJobs.ts:14:53)
      at fulfilled (test/testWalletJobs.ts:5:58)
      at processTicksAndRejections (node:internal/process/task_queues:94:5)      
```

**Comment by alex-miller-0** [comment]
@douglance Looks like just one more thing to fix

**Review by alex-miller-0 — APPROVED** [review]

**Comment by douglance** [comment]
@alex-miller-0 I fixed that error. I'm not able to get those tests to succeed, so I can't guarantee those tests pass.

**Comment by alex-miller-0** [comment]
@douglance just tested - it works 👍

**Pull request merged**
