### PR TITLE
Updates wallet-jobs tests to handle mnemonic storage operations

### PR DESCRIPTION
**Pull request by alex-miller-0**
These changes correspond to a fw branch I am working on (`tlv-cfg`)
but should also work with the latest `dev`.
Also updates the tests more generally to avoid requiring user
signing authorizations (these are supposed to be automated).

### CODE REVIEW

**Review by douglance — APPROVED** [review]
Three of the tests fail for me using the current card applet. I'm not sure when I'll be able to get the latest applet flashed, so I'll approve for now, as to not block.

**Comment by alex-miller-0** [comment]
@douglance can you try this again with the `release-0.16.0` fw branch please

**Review by douglance — APPROVED** [review]
All tests pass

**Comment by alex-miller-0** [comment]
Doug tested and it is passing ✅

**Pull request merged**
